### ISSUE TITLE
Typo in recent article

### ISSUE THREAD

**Issue by moreheadm** [nickdrozd/nickdrozd.github.io#1]
Proving your point from earlier in the article, your most recent article has an uncaught typo. From the description of the third mistake:

Then x = 10a + b, y = 10c + d, and xy = (10a + b)(10c + d). FOILing that out gives xy = 100ac + 10ad + 10bc + bd. At this point we still have the expected n2 = 4 single-digit multiplications: ac, ad, bc, bd. Now add and subtract 10ac + 10bc.

This last sentence should be: "Now add and subtract 10ac + 10bd"

I thought you might like to know. Thanks for the really cool article.

**Comment by nickdrozd** [comment]
Great catch! There was a mundane typo that everybody jumped on, but you're the first one to point out this substantial technical typo. Before I fix it, does the rest of the math check out to you?

**Comment by moreheadm** [comment]
Yeah I didn't notice any other mistake in the math in that section.

**Comment by nickdrozd** [comment]
Thanks!
