### ISSUE TITLE
there is no such thing as a "standard Mac keyboard"

### ISSUE THREAD

**Issue by brandelune** [nickdrozd/nickdrozd.github.io#2]
I work on a 2015 mbp and the bottom row is:
caps | alt/option | command | toggle alphabetical input | space | toggle kana input | command | fn | arrows

The left "column" is:
esc
1 | ! | ぬ
tab
control
shift
caps

the right column is:
on/off
delete
enter/return
shift
arrows

That is a "standard" Japanese Apple keyboard, and I'm guessing that a lot of locales have keyboard variations based on their needs.

Maybe you should specify "US qwerty keyboard" ?

**Comment by nickdrozd** [comment]
Thanks for pointing that out. I added a note about Japanese keyboards; please take a look to see if it's accurate and let me know if it isn't. AFAICT, the Japanese Mac keyboard is the only one that deviates from the Fn/Ctrl/Optn/Cmd layout, so I feel comfortable sticking with the word "standard".

-- Nick "ネコ" Drozd

**Comment by brandelune** [comment]
Thank you for the reply. I thought there would be slightly more variations but the magic kb in various languages does seem to stick to the pattern you describe:
https://www.apple.com/shop/product/MLA22LC/A/magic-keyboard-chinese-pinyin
And thank you for the article too.
